config/routes.rb
Rails.application.routes.draw do

  # Topページに[root_path]を設定
  root to: "homes#top"

  # devise のモデルを作成したことでルーティングが自動的に追加
  # devise を使用する際に URL として users を含むことを示している
  devise_for :users

   get '/homes/about' => 'homes#about', as: 'about'

  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    # post_imagesと親子関係（「親」に対して「子」される）
      # ⇩ resourceとなっている点に注目!(単数形にすると、/:idがURLに含まれなくなる。)
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    # ↑ ネストする(params[:post_image_id]でPostImageのidが取得できるようになります。)
  end

  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
   # アソシエーション( Favorite : User = N : 1 )(Userは単数系)
  belongs_to :user
   # アソシエーション( Favorite : PostImage = N : 1 )(PostImageは単数系)
  belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
 # アソシエーション( PostComment : User = N : 1 )(Userは単数系)
  belongs_to :user
 # アソシエーション(PostComment : PostImage = N : 1 )(PostImageは単数系)
  belongs_to :post_image
  
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  # ActiveStorage(画像の投稿、表示するためのもの)
  has_one_attached :image

  # アソシエーション(Postimage : User = N : 1 )（belongs_to = Userに属するということ）
  belongs_to :user
    # PostImage モデルに関連付けられるのは、1 つの User モデル
    # このため、単数形の「user」になっている点に注意
    
  # アソシエーション(PostImage : PostComment = 1 : N )(PostCommentsは複数形)
  has_many :post_comments, dependent: :destroy
  
  # アソシエーション(PostImage : Favorites = 1 : N )(Favoritesは複数形)
  has_many :favorites, dependent: :destroy
  
  # バリデーションの実装(フォームの未入力のチェックを行い、エラーメッセージを表示)
  validates :shop_name, presence: true
   validates :image, presence: true
    
    # 画像が投稿されなかった時に代わりの画僧を表示させる
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end  
    image
  end
  # 引数で渡されたユーザーが存在するか？
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  #  ⇩アソシエーション(User : PostImages = 1 : N )( N は複数形）,   ⇩ユーザーIDを消したら投稿も消える
  has_many :post_images, dependent: :destroy
  
  #   ⇩アソシエーション(User : PostComments = 1 : N )( N は複数形）
  has_many :post_comments, dependent: :destroy
  
  #   ⇩アソシエーション(User : Favorites = 1 : N )( N は複数形）
  has_many :favorites, dependent: :destroy
  
 # プロフィール画像
  # profile_imageという名前でActiveStorageでプロフィール画像を保存できるように設定
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    # 画像サイズの変換
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #ログイン認証が済んでいない状態でトップページ以外の画面にアクセスしても、ログイン画面へリダイレクトする
  before_action :authenticate_user!, except: [:top]

  # deviseのコントローラは直接修正できないため、全てのコントローラに対する処理を行える権限を持つ、ApplicationControllerに
  # deviseのストロングパラメータを編集を記述する必要があります。
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  # aboutページをサインイン後の遷移先に設定
   def after_sign_in_path_for(resource)
     post_images_path
   end
   
  # aboutページをサインアウト後の遷移先に設定
   def after_sign_out_path_for(resource)
     about_path
   end

# privateは記述をしたコントローラ内でしか参照できません。
# 一方、protectedは呼び出された他のコントローラからも参照することができます。
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # ストロングパラメータと同様の機能↑
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    post_image = PostImage.find(params[:post_image_id])
                                     #  （     A       :     B        ) = ( Bという値を A という名前で受け取る)
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    post_image = PostImage.find(params[:post_image_id])
    # find_by は、特定の条件にマッチした最初のレコードを検索(取得できるデータは1件のみ)
    #.            モデル名にfind_byメソッドをつなげて引数を1つ以上指定
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end  
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    # ネストしたURLを作成することでparams[:post_image_id]でPostImageのidが取得できるようになります
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end
  
  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end
  
  def create
    @post_image = PostImage.new(post_image_params)
    # current_user は、ログイン中のユーザーの情報を取得できる便利な記述(devise を導入しないと使用することができない)
    @post_image.user_id = current_user.id
   if @post_image.save
      redirect_to post_images_path
   else
      render :new
   end  
  end

  def index
    # 1ページ分の決められた数のデータだけを、新しい順に取得するように変更
    @post_images = PostImage.page(params[:page])
  end
  
  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end
  
  def destroy
    post_image = PostImage.find(params[:id])
    post_image.destroy
    redirect_to post_images_path
  end
  
  
  # 投稿データのストロングパラメータ
  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # 各アクションを実行する前に実行したい処理を指定(before_action)
    # メソッドは一番下に定義してる
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    
  # @user.post_imagesに格納されているデータは複数あるため,
  # 関連づけられているモデルのカラムを操作することはできません。
    @post_images = @user.post_images.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
  
  # 他のユーザーからのアクセス制限(is_matching_login_userというメソッドにまとめる)
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to post_images_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>Aboutページ</h1>

app/views/homes/top.html.erb
<h1>Topページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro</title>
   
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <!--FontAwesomeを導入-->
      <script src="https://kit.fontawesome.com/0d9a4945d7.js" crossorigin="anonymous"></script>
     <!--Bootstrapの導入-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
         <!--⇩ ログインしている時としていない時で表示を分けることができる-->
            <% if user_signed_in? %>
             <!--ログインしてた場合の表示-->
             
             <!--ログアウトはHTTPメソッドがDELETEであることに注意!
                  link_toのHTTPメソッドは、特に設定しなければGETになります。-->
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿フォーム', new_post_image_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <!--ログインしてなかった場合の表示-->
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>善良な市民同士で無差別に食欲を煽るSNS</p>
            <%= image_tag('logo-white.png') %>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/post_images/_list.html.erb
<!--部分テンプレートファイル-->
<div class="card-list-container py-5">
 <% post_images.each do |post_image| %>
<!--部分テンプレートが呼び出されたときに、
Viewから渡される変数が使えるようにローカル変数を使います。-->

  <div class="card w-50 mx-auto mt-4 shadow-lg">

  <%= link_to post_image_path(post_image.id) do %>
  <!--image_tagを使いpost_imageにActiveStorageで設定したimageを表示。
      post_image.get_imageの部分はPostImageモデル内に記述したメソッドを呼び出している-->
    <%= image_tag post_image.get_image, class:"card-img-top"; %>
  <% end %>
  
    <div class="card-body">
      <div class="row">
        <div class="col-4">
          <%= image_tag post_image.user.get_profile_image(100,100), class:"mt-3 rounded-circle"; %>
        </div>
         <div class="col-8">
           <p class="card-title">
            <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
            <% end %>
           </p>
           <p class="card-text">説明：<%= post_image.caption %></p>
           <span><i class="fas fa-user"></i> By <%= post_image.user.name %> ｜ </span>
           <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %></span>
         </div>
      </div>
    </div>
  </div>
<% end %>
<!--ページネーション-->
<%= paginate post_images %>

</div>

app/views/post_images/index.html.erb
<!--投稿一覧-->

<!--部分テンプレートを呼び出せるように設定-->
<!--      [部分テンプレートファイル名(アンダースコアは省略)], [←のローカル変数]:[渡す値] -->
<%= render 'list', post_images: @post_images %>

app/views/post_images/new.html.erb
<!--投稿作成画面-->
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @post_image.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @post_image.errors.count %>件のエラーが発生しました
            </h6>
            <% @post_image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @post_image do |f| %>
          <%= f.file_field :image, accept: "image/*", class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div>
  <%= image_tag @post_image.get_image %>
  <p>ショップ名：<%= @post_image.shop_name %></p>
  <p>説明：<%= @post_image.caption %></p>
  <p>投稿ユーザー画像：<%= image_tag @post_image.user.get_profile_image(100,100) %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <!--%Y/%m/%d'の記述で、年/月/日のフォーマットへ変換-->
  <p>投稿日：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>

  <!--削除ボタン-->
  <!--投稿した本人以外が削除できないように、投稿した本人がログインしている場合だけ画面に削除リンクを表示させる-->
  <% if @post_image.user == current_user %>
    <%= link_to "投稿削除", post_image_path(@post_image), method: :delete %>
  <% end %>
  <!--いいね機能-->
  　<!--favorited_by?　は引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べます。-->
  <% if @post_image.favorited_by?(current_user) %>
    <p>
      <!--いいねしてたら-->
      <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
        ❤️<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
    <!--いいねしてなかったら-->
    <% else %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
</div>
<!--コメント-->
<div>
  <p>コメント件数：<%= @post_image.post_comments.count %></p>
  <!--コメントした人について-->
  <% @post_image.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
    <!--コメント削除ボタン-->
    <% if post_comment.user == current_user %>
      <%= link_to "コメント削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
    <% end %>
  <% end %>
</div>
<!--コメント入力フォーム-->
<div>
  <%= form_with model: [@post_image, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>

<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>

  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>

  <%= f.submit "変更を保存" %>

<% end %>

app/views/users/show.html.erb
<!-- ユーザーの詳細 -->
<div class="profile-container">
  <h3 class="profile-name"><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <!--サインインしているユーザーを取得する(deviseのヘルパーメソッド)-->
  <% if @user.id == current_user.id %>
  <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
</div>

<!-- ユーザーの投稿一覧 -->
  <!--部分テンプレートを呼び出せるように設定-->
<%= render 'post_images/list', post_images: @post_images %>
  <!--違うフォルダに部分テンプレートがあるから、フォルダ名も指定する事！-->